# Nonlinear Regression Models

```{r chapter-07-startup, include = FALSE}
knitr::opts_chunk$set(fig.path = "figures/")
library(knitr)
library(tidymodels)
library(patchwork)

caching <- TRUE

cores <- parallel::detectCores()
if (!grepl("mingw32", R.Version()$platform)) {
 library(doMC)
 registerDoMC(cores = cores)
} else {
  library(doParallel)
  cl <- makePSOCKcluster(cores)
  registerDoParallel(cl)
}
```

```{r chapter-07-prereq}
library(tidymodels)
load("solubility_data.RData")

solubility_rec <- 
  recipe(solubility ~ ., data = solubility_train) %>% 
  step_zv(all_predictors()) %>% 
  step_YeoJohnson(all_predictors())

normalized_rec <- 
  solubility_rec %>% 
  step_normalize(all_predictors())

solubility_wflw <- 
  workflow() %>% 
  add_recipe(solubility_rec)

rs_ctrl <- control_resamples(save_pred = TRUE)
gd_ctrl <- control_grid(save_pred = TRUE, parallel_over = "everything")
bo_ctrl <- control_bayes(save_pred = TRUE, verbose = TRUE)

rmse_stats <- metric_set(rmse)
```

## Neural Networks

```{r chapter-07-nnet, cache = caching}
nnet_spec <- 
 mlp(hidden_units = tune(), penalty = tune(), epochs = tune()) %>% 
 # nnet() has a fixed limit on the number of parameters that is fairly
 # low. We set if to work with the largest network that we'll make. 
 set_engine("nnet", MaxNWts = 2600) %>% 
 set_mode("regression")

nnet_wflow <- 
 workflow() %>% 
 add_model(nnet_spec) %>% 
 add_recipe(normalized_rec)

nnet_param <- 
 nnet_wflow %>% 
 parameters() %>% 
 update(penalty = penalty(c(-10, 1)))

set.seed(123)
nnet_bo <-
 nnet_wflow %>%
 tune_bayes(
  solubility_folds,
  initial = 5,
  iter = 10,
  param_info = nnet_param,
  control = bo_ctrl,
  metrics = rmse_stats
 )

autoplot(nnet_bo, type = "performance")
```


## Multivariate Adaptive Regression Splines

```{r chapter-07-mars, cache = caching}
mars_spec <- 
  mars(num_terms = tune(), prod_degree = tune(), prune_method = "none") %>% 
  set_engine("earth") %>% 
  set_mode("regression")

mars_wflow <- 
  workflow() %>% 
  add_model(mars_spec) %>% 
  add_recipe(solubility_rec)

mars_grid <- tidyr::crossing(num_terms = 2:50, prod_degree = 1:2) 

mars_tune <-
 mars_wflow %>%
 tune_grid(
  solubility_folds,
  grid = mars_grid,
  control = gd_ctrl,
  metrics = rmse_stats
 )

autoplot(mars_tune)
```

## Support Vector Machines

```{r chapter-07-svm-radial, cache = caching}
svm_r_spec <- 
  svm_rbf(cost = tune(), rbf_sigma = tune()) %>% 
  set_engine("kernlab") %>% 
  set_mode("regression")

svm_r_wflow <- 
  workflow() %>% 
  add_model(svm_r_spec) %>% 
  add_recipe(normalized_rec)

set.seed(4983)
svm_r_tune <-
 svm_r_wflow %>%
 tune_grid(
  solubility_folds,
  grid = 25,
  control = gd_ctrl,
  metrics = rmse_stats
 )

autoplot(svm_r_tune)
```


```{r chapter-07-svm-poly, cache = caching}
svm_p_spec <- 
  svm_poly(cost = tune(), degree = tune()) %>% 
  set_engine("kernlab") %>% 
  set_mode("regression")

svm_p_wflow <- 
  workflow() %>% 
  add_model(svm_p_spec) %>% 
  add_recipe(normalized_rec)

svm_p_param <- 
 svm_p_wflow %>% 
 parameters() %>% 
 update(degree = prod_degree())

set.seed(762)
svm_p_tune <-
 svm_p_wflow %>%
 tune_grid(
  solubility_folds,
  grid = 25,
  param_info = svm_p_param,
  control = gd_ctrl,
  metrics = rmse_stats
 )

autoplot(svm_p_tune)
```


## K-Nearest Neighbors

```{r chapter-07-knn, cache = caching}
knn_spec <- 
  nearest_neighbor(neighbors = tune(), dist_power = tune(), weight_func = tune()) %>% 
  set_engine("kknn") %>% 
  set_mode("regression")

knn_wflow <- 
  workflow() %>% 
  add_model(knn_spec) %>% 
  add_recipe(normalized_rec)

set.seed(205)
knn_tune <-
  knn_wflow %>%
  tune_grid(solubility_folds, grid = 25, control = gd_ctrl, metrics = rmse_stats)

autoplot(knn_tune)
```


```{r chapter-07-teardown, include = FALSE}
if (grepl("mingw32", R.Version()$platform)) {
 stopCluster(cl)
} 
```
