# Remedies for Severe Class Imbalance

```{r chapter-16-startup, include = FALSE}
knitr::opts_chunk$set(fig.path = "figures/")
library(tidymodels)

caching <- TRUE

cores <- parallel::detectCores()
if (!grepl("mingw32", R.Version()$platform)) {
 library(doMC)
 registerDoMC(cores = cores)
} else {
  library(doParallel)
  cl <- makePSOCKcluster(cores)
  registerDoParallel(cl)
}
```


The R packages used in this chapter are: `r pkg_text(c("tidymodels", "C50", "rpart", "baguette",
"xgboost", "ranger"))`. 


## Case Study: Predicting Caravan Policy Ownership

```{r chapter-16-data}
library(tidymodels)

load("RData/tic_data.RData")

n <- nrow(tic_data)

# Split into evaluation set and other
set.seed(1601)
tic_split_eval <- initial_split(tic_data, strata = class, prop = 983/n)

tic_eval <- training(tic_split_eval)

# Now split into a training and test set
set.seed(1602)
tic_split <- initial_split(testing(tic_split_eval), 
                           strata = class, prop = 6877/(6877 + 1962))


tic_training <- training(tic_split)
tic_testing  <-  testing(tic_split)

set.seed(1603)
tic_folds <- vfold_cv(tic_training, strata = class)
```

## The Effect of Class Imbalance


## Model Tuning

## Alternate Cutoffs


## Adjusting Prior Probabilities


## Unequal Case Weights


## Sampling Methods


## Cost-Sensitive Training

```{r chapter-16-cart-costs}
library(baguette)

cart_cost_spec <- 
 bag_tree(class_cost = tune()) %>% 
 set_engine("C5.0", times = 99) %>% 
 set_mode("classification")

cart_cost_wflow <- 
 workflow() %>% 
 add_model(cart_cost_spec) %>% 
 add_variables(outcomes = class, predictors = everything())

class_metrics <- metric_set(kap, roc_auc, sensitivity, specificity)

gd_ctrl <- control_grid(save_pred = TRUE, save_workflow = TRUE, 
                        parallel_over = "everything")

set.seed(1604)
cart_cost_tune <-
 cart_cost_wflow %>% 
 tune_race_anova(resamples = tic_folds, 
           grid = tibble(class_cost = c(1/tt, seq(1, 20, length.out = 10))), 
           # control = gd_ctrl,
           control = control_race(verbose_elim = TRUE),
           metrics = class_metrics)

set.seed(1604)
cart_cost_tune <-
 cart_cost_wflow %>% 
 tune_grid(resamples = tic_folds, 
           grid = tibble(class_cost = c(1/tt, seq(1, 20, length.out = 10))), 
           control = gd_ctrl,
           metrics = class_metrics)


set.seed(1604)
cart_cost_bo <-
 cart_cost_wflow %>% 
 tune_bayes(resamples = tic_folds, 
           param_info = parameters(class_cost(c(0, 50))), 
           initial = 5,
           iter = 20,
           control = control_bayes(verbose = TRUE, parallel_over = "everything", no_improve = Inf),
           metrics = class_metrics)


```

```{r}
cart_cost_tune %>% 
 collect_metrics() %>% 
 filter(.metric %in% c("sens", "spec")) %>% 
 select(class_cost, .metric, mean) %>% 
 ggplot(aes(x = class_cost, y = mean, col = .metric)) + 
 geom_point() + 
 geom_line() + 
 facet_wrap(~ .metric)
```